### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by eMerzh** [juanda99/arasaac-frontend#91]
Hey, 
👋  hello @juanda99 from belgium,
we know arasaac and araword for a few years now, because it runs on linux and is open source.
My Gf is a speach terapist and use your tools on a daily basis...
we discovered the new website 👍  good job... 
and thanks

Wanted to let you know that make it available in french is really appreciated here and make it open too!
How can we help you build this (technically or not)?
do not hesitate to leave a few things in the issues i might pick something if i have some time available.

really nice project ❤️

**Comment by juanda99** [comment]
Thanks @eMerzh . 
The time, money and people we can dedicate to this project depend on its success, so sharing the web with other french speakers is a great help for us. Right now 50% of ARASAAC users are from Spain and 75% from Spanish speaking countries. Just 4% from french speaking countries. 
Technically a big help would be contribute with tools using the new API.  Beginning on January we will try to build some of them. A new Araword would our first aim,  integrating natural processing language.
